name: "Analyse code"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Static Analysis"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: "Running staticcheck"
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"

    - name: "Installing golint"
      run: "go install golang.org/x/lint/golint@latest"

    - name: "Installing ineffassign"
      run: "go install github.com/gordonklaus/ineffassign@latest"

    - name: "Running golint"
      run: "golint ./..."

    - name: "Running go vet"
      run: "go vet ./..."

    - name: "Running go ineffassign"
      run: "ineffassign ./..."
