name: "Static Analysis"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Staticcheck"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"

    - run: "go install golang.org/x/lint/golint@latest"
    - run: "golint ./..."

    - run: "go vet ./..."
